set pagesize 100
set linesize 200


---PL SQL

---PL/SQL block to calculate and update the total amount paid for each order:
DECLARE
  v_order_id orders.order_id%TYPE;
  v_total_amount NUMBER(10, 2);
BEGIN
  FOR rec IN (select order_id from orders)
  LOOP
    v_order_id := rec.order_id;
    
    select SUM(amount) INTO v_total_amount
    from payments
    WHERE order_id = v_order_id;
    
    UPDATE payments
    SET amount= v_total_amount
    WHERE order_id = v_order_id;
    
    COMMIT;
  END LOOP;
END;
/




--- PL/SQL block to retrieve customer details and the total number of orders placed:
DECLARE
  v_customer_id customers.customer_id%TYPE;
  v_customer_name customers.name%TYPE;
  v_order_count NUMBER;
BEGIN
  FOR rec IN (select customer_id, name from customers)
  LOOP
    v_customer_id := rec.customer_id;
    v_customer_name := rec.name;
    
    select COUNT(*) INTO v_order_count
    from orders
    WHERE customer_id = v_customer_id;
    
    DBMS_OUTPUT.PUT_LINE('Customer Name: ' || v_customer_name);
    DBMS_OUTPUT.PUT_LINE('Total Orders: ' || v_order_count);
    DBMS_OUTPUT.PUT_LINE('-------------------------');
  END LOOP;
END;
/



---PL/SQL block to delete all orders placed by a specific customer:
DECLARE
  v_customer_id customers.customer_id%TYPE:= 1; -- orders of customerid to be deleted
BEGIN
  DELETE from orders
  WHERE customer_id = v_customer_id;
  
  COMMIT;
  
  DBMS_OUTPUT.PUT_LINE('All orders for Customer ID ' || v_customer_id || ' have been deleted.');
END;
/





--- PL/SQL block to retrieve all customers who have pending orders:
DECLARE
  v_customer_id customers.customer_id%TYPE;
  v_customer_name customers.name%TYPE;
BEGIN
  FOR rec IN (select c.customer_id, c.name
              from customers c
              WHERE EXISTS (
                select 1
                from orders o
                WHERE o.customer_id = c.customer_id
                  AND o.status = 'Pending'
              ))
  LOOP
    v_customer_id := rec.customer_id;
    v_customer_name := rec.name;
    
    DBMS_OUTPUT.PUT_LINE('Customer ID: ' || v_customer_id);
    DBMS_OUTPUT.PUT_LINE('Customer Name: ' || v_customer_name);
    DBMS_OUTPUT.PUT_LINE('-------------------------');
  END LOOP;
END;
/


---PL/SQL block to calculate the total revenue generated by each customer:
DECLARE
  v_customer_id customers.customer_id%TYPE;
  v_customer_name customers.name%TYPE;
  v_total_revenue NUMBER(10, 2);
BEGIN
  FOR rec IN (select c.customer_id, c.name
              from customers c
              JOIN orders o ON c.customer_id = o.customer_id
              JOIN products p ON o.product_id = p.product_id)
  LOOP
    v_customer_id := rec.customer_id;
    v_customer_name := rec.name;
    
    select SUM(o.quantity * p.price) INTO v_total_revenue
    from orders o
    JOIN products p ON o.product_id = p.product_id
    WHERE o.customer_id = v_customer_id;
    
    DBMS_OUTPUT.PUT_LINE('Customer ID: ' || v_customer_id);
    DBMS_OUTPUT.PUT_LINE('Customer Name: ' || v_customer_name);
    DBMS_OUTPUT.PUT_LINE('Total Revenue: $' || v_total_revenue);
    DBMS_OUTPUT.PUT_LINE('-------------------------');
  END LOOP;
END;
/

